learning_users/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns=[
    url(r'^register/$',views.register, name='register'),
    url(r'^user_login/$',views.user_login,name='user_login')

]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path(r'admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special'),
    url(r'^basicapp/', include('basicapp.urls'))
]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics' , blank = True)


    def __str__(self):
        return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username' , 'email' , 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site' , 'profile_pic')

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import Userform,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect , HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')


@login_required
def special(request):
    return HttpResponse("YOU ARE LOGGED IN")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method=='POST':
        user_form = Userform(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors , profile_form.errors)

    else:
        user_form = Userform()
        profile_form = UserProfileInfoForm()

    return render(request , 'basicapp/register.html',
                             {'user_form':user_form,
                               'profile_form':profile_form,
                                'registered':registered})




def user_login(request):


    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username , password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("SOMEONE ELSE TRIED TO LOGIN BUT FAILED")
            print(" usernsme {} password {}".format(username,password))
            return HttpResponse("invalid login credentials")

    else:
        return render(request,'basicapp/login.html',{})

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class = 'navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class = 'nav navbar-nav'>
          <li><a class = "navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class = "navbar-link" href="{% url 'basicapp:register' %}">Registration</a></li>

          {% if user.is_authenticated %}
          <li><a class = "navbar-link" href="{% url 'logout' %}">logout</a></li>
            {% else %}
            <li><a class = "navbar-link" href="{% url 'basicapp:user_login' %}">login</a></li>
            {% endif  %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>





  </body>
</html>

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body_block%}

<div class="jumbotron">
  <h1>DJANGO LEVEL FIVE</h1>
</div>

{% endblock %}

learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html '%}
{% block body_block %}

<div class="jumbotron">
  <h1>login</h1>
  <form  action="{% url 'basicapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">username</label>
    <input type="text" name="username" placeholder="username">
    <label for="password">password</label>
    <input type="password" name="password" >
    <input type="submit" name="" value="login">

  </form>

</div>



{% endblock %}

learning_users/templates/basicapp/register.html
{% extends "basicapp/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>THANKS FOR REGISTERING</h1>
  {% else %}
    <h1>Register Here</h1>
    <h3>FILL OUT THIS FORM</h3>
    <form enctype="multipart/form-data" method="post">
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      {% csrf_token %}
      <input type="submit" name="" value="register">

    </form>
  {% endif %}

</div>
{% endblock %}